workflows:
  android-free-build-optimized:
    name: Android Unsigned (Clean Version)
    max_build_duration: 60
    instance_type: linux
    environment:
      flutter: stable
      groups:
        - magic_vars
    scripts:
      - name: Initialize
        script: flutter pub get
      - name: Build & Package
        script: |
          flutter clean
          flutter build apk --release

          APK_PATH=$(find build/app/outputs/flutter-apk -name "*.apk" | head -n 1)

          mkdir -p build/android/apk
          cp "$APK_PATH" build/android/apk/app-release.apk
    artifacts:
      - build/android/apk/app-release.apk
