workflows:
  android-free-build-optimized:
    name: Android Unsigned (Clean Version)
    max_build_duration: 60
    instance_type: linux
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get

      - name: Build APK
        script: |
          flutter clean
          flutter build apk --release

          mkdir -p build/android/apk
          cp build/app/outputs/flutter-apk/app-release.apk build/android/apk/app-release.apk

    artifacts:
      - build/android/apk/app-release.apk
